[package]
name = "wasmtime-py"
version = "0.2.0"
authors = ["The Wasmtime Project Developers"]
description = "Python extension for Wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "python"]
edition = "2018"

[lib]
name = "_wasmtime"
crate-type = ["cdylib"]

[dependencies]
cranelift-codegen = { path = "../../../cranelift/cranelift-codegen" }
cranelift-native = { path = "../../../cranelift/cranelift-native" }
cranelift-entity = { path = "../../../cranelift/cranelift-entity" }
cranelift-wasm = { path = "../../../cranelift/cranelift-wasm" }
cranelift-frontend = { path = "../../../cranelift/cranelift-frontend" }
wasmtime-environ = { path = "../../wasmtime-environ" }
wasmtime-interface-types = { path = "../../wasmtime-interface-types" }
wasmtime-jit = { path = "../../wasmtime-jit" }
wasmtime-runtime = { path = "../../wasmtime-runtime" }
target-lexicon = { version = "0.4.0", default-features = false }
failure = "0.1"
region = "2.0.0"
wasmparser = "0.37.1"

[dependencies.pyo3]
version = "0.7.0-alpha.1"
features = ["extension-module"]
