[package]
name = "cranelift-simplecompiler"
version = "0.63.0"
authors = ["The Cranelift Project Developers"]
description = "A single function compiler for Cranelift"
repository = "https://github.com/bytecodealliance/wasmtime"
documentation = "https://docs.rs/cranelift-simplejit"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
edition = "2018"

[dependencies]
cranelift-codegen = { path = "../codegen", version = "0.63.0" }
cranelift-frontend = { path = "../frontend", version = "0.63.0" }
cranelift-native = { path = "../native", version = "0.63.0" }
cranelift-reader = { path = "../reader", version = "0.63.0" }
memmap = "0.7.0"
log = "0.4.8"
thiserror = "1.0.16"

