[package]
name = "wasmtime-wasi"
version = "0.0.0"
authors = ["The Cranelift Project Developers"]
publish = false
description = "WASI API support for Wasmtime"
categories = ["wasm"]
repository = "https://github.com/CraneStation/wasmtime"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"

[dependencies]
wasmtime-runtime = { path = "../wasmtime-runtime" }
wasmtime-environ = { path = "../wasmtime-environ" }
wasmtime-jit = { path = "../wasmtime-jit" }
wasi-common = { git = "https://github.com/kubkon/wasi-common", branch = "alex-rewrite" }
cranelift-codegen = { version = "0.35.0", features = ["enable-serde"] }
cranelift-entity = "0.35.0"
cranelift-wasm = { version = "0.35.0", features = ["enable-serde"]  }
target-lexicon = "0.4.0"
log = { version = "0.4.6", default-features = false }

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "CraneStation/wasmtime" }
