[package]
name = "cranelift-fuzz"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1.0.0", features = ["derive"] }

cranelift = { path = "../umbrella" }
cranelift-filetests = { path = "../filetests" }
cranelift-interpreter = { path = "../interpreter" }
cranelift-fuzzgen = { path = "../fuzzgen" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzzgen"
path = "fuzz_targets/fuzzgen.rs"
test = false
doc = false
